export const UPDATE_HEADING_FONT = "UPDATE_HEADING_FONT";
export const UPDATE_BODY_FONT = "UPDATE_BODY_FONT";
export const TOGGLE_LOCK_HEADING_FONT = "TOGGLE_LOCK_HEADING_FONT";
export const TOGGLE_LOCK_BODY_FONT = "TOGGLE_LOCK_BODY_FONT";
export const UPDATE_HEADING_TEXT = "UPDATE_HEADING_TEXT"
export const UPDATE_BODY_TEXT = "UPDATE_BODY_TEXT"
